[tool.ruff]
# See https://docs.astral.sh/ruff/configuration/ for defaults.
target-version = "py39"

[tool.ruff.lint]
# Default select: ["E4", "E7", "E9", "F"]
select = ["E4", "E7", "E9", "F", "I", "UP"]

[tool.ruff.lint.isort]
known-first-party = ["bro_exchange"]
