namespace = {
    "FRD_registration": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_replace": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
        },
    "FRD_GEM_Configuration_registration": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_GEM_Configuration_replace": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_GEM_Configuration_delete": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_Closure_registration": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_Closure_delete": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
        },
    "FRD_GEM_Measurement_registration": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_GEM_Measurement_delete": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_GEM_Measurement_replace": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_GEM_Measurement_insert": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_GEM_Measurement_move": {
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_EMM_InstrumentConfiguration_registration":{
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_EMM_InstrumentConfiguration_replace":{
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_EMM_InstrumentConfiguration_delete":{
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_EMM_Measurement_registration":{
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_EMM_Measurement_replace":{
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_EMM_Measurement_insert":{
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_EMM_Measurement_move":{
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
    "FRD_EMM_Measurement_delete":{
        None: "http://www.broservices.nl/xsd/isfrd/1.0",
        "frdcom": "http://www.broservices.nl/xsd/frdcommon/1.0",
        "brocom": "http://www.broservices.nl/xsd/brocommon/3.0",
        "swe": "http://www.opengis.net/swe/2.0",
        "gml": "http://www.opengis.net/gml/3.2",
        "xlink": "http://www.w3.org/1999/xlink",
        "xsi": "http://www.w3.org/2001/XMLSchema-instance",
    },
}

xsi_schemalocation = (
    "http://www.broservices.nl/xsd/isfrd/1.0 ../../XSD/isfrd-messages.xsd"
)

